web-server:
    build: ./web-server
    links:
        - api-proxy
    ports:
        - "80:80"
    volumes:
        - "./web-server/engine/:/usr/local/apache2/cgi-bin/"

api-proxy:
    build: ./api-proxy
    ports:
        - "1234:80"
