FROM    nginx

ADD     --chown=100:101 ./app.conf /etc/nginx/conf.d/app.conf 

LABEL   author="Sergej Nowoshilow"
LABEL   maintainer="Sergej Nowoshilow"
LABEL   email="Sergej.Nowoshilow@imp.ac.at"
LABEL   description="This container image contains a small proxy server that allows to use Axolotl-Omics API"
LABEL   version="1.0"